---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: centos-7
  - name: ubuntu-16.04
  - name: debian-9

provisioner:
  name: salt_solo
  formula: apache
  require_chef: false
  data_path: test/shared
  pillars:
    top.sls:
      base:
        '*':
          - apache
    apache.sls:
      apache:
        manage_service_states: False
        mod_security:
          crs_install: True
          manage_config: True
          sec_rule_engine: 'On'
          sec_request_body_access: 'On'
          sec_request_body_limit: '14000000'
          sec_request_body_no_files_limit: '114002'
          sec_request_body_in_memory_limit: '114002'
          sec_request_body_limit_action: 'Reject'
          sec_pcre_match_limit: '15000'
          sec_pcre_match_limit_recursion: '15000'
          sec_debug_log_level: '3'

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - apache
            - apache.mod_security
  - name: apache_norestart
    provisioner:
      state_top:
        base:
          '*':
            - apache
      pillars:
        apache.sls:
          apache:
            manage_service_states: False
